
services:
  db:
    image: mysql:latest
    container_name: CL2015_BDD
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: BDDCAFE2025
      MYSQL_USER: BDDCAFE2025_user
      MYSQL_PASSWORD: secret
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./docker/mysql-init:/docker-entrypoint-initdb.d

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: CL2015_PHPMyAdmin
    restart: always
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: root
    ports:
      - "8082:80"
    depends_on:
      - db

  mailhog: # !Important Nom du service 
    image: mailhog/mailhog:latest
    container_name: CL2015_Mail
    logging:
      driver: 'none'  # Désactiver les logs car il y en a beaucoup
    ports:
      - 1025:1025 # Serveur SMTP
      - 8025:8025 # Interface web
volumes:
  db_data: 
